name: CI Build Linux
on: [push]

jobs:
  build:
    name: Linux build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # - name: Update distro
      #   run: sudo apt update
      # - name: Upgrade distro
      #   run: sudo apt upgrade

      - name: Install build dependencies
      # run: sudo apt install cmake debhelper-compat intltool libcairomm-1.0-dev libdjvulibre-dev libenchant-2-dev libgtkmm-3.0-dev libgtksourceviewmm-3.0-dev libgtkspellmm-3.0-dev libjpeg-dev libjson-glib-dev libpangomm-1.4-dev libpodofo-dev libpoppler-glib-dev libpoppler-qt6-dev libqtspell-qt6-dev libquazip1-qt6-dev libsane-dev libtesseract-dev libxml++2.6-dev libzip-dev python3-gi qt6-base-dev uuid-dev
        run: sudo apt install debhelper cmake intltool libdjvulibre-dev libgtkspellmm-3.0-dev libgtkmm-3.0-dev libgtksourceviewmm-3.0-dev libcairomm-1.0-dev libpoppler-glib-dev libtesseract-dev libsane-dev qtbase5-dev qttools5-dev qttools5-dev-tools libqtspell-qt5-dev libpoppler-qt5-dev libjson-glib-dev libxml++2.6-dev libpodofo-dev libquazip5-dev libzip-dev python3-gi uuid-dev
      - uses: actions/checkout@v4.2.2

      - name: Build application
        run: |
          mkdir -p build
          cd build
          cmake -DINTERFACE_TYPE=gtk ..
          make

      - name: Build Packages
        run: |
          pwd
          cd build
          ../packaging/AppImage/makePkg.sh -y Linux 64
          ls -l ../packaging/*

      - name: Reset ci-latest tag
        run: |
          VERSION=${{ steps.version_number.outputs.version }}
          git config --global user.email "ci@github.com"
          git config --global user.name "Github CI"
          git tag -d ci-latest || true
          git push origin :ci-latest || true
          git tag -m ci-latest ci-latest
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1.18.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          tag: ci-latest
          name: CI Build
          draft: false
          prerelease: true
          replacesArtifacts: true
          artifacts: "
            ./packaging/gImageReader_*_Linux_x86_64_64bit.tgz
            ./packaging/gImageReader_*_Linux_x86_64_64bit.AppImage
          "
